language: java
jdk:
- oraclejdk8

sudo: required

env:
  global:
  - NODE_ENV=test
  - PGPORT=5433
  - PGHOST=localhost

services:
  - postgresql

addons:
  apt:
    sources:
    - precise-pgdg-9.4
    packages:
    - postgresql-9.4
    - postgresql-contrib-9.4
  postgresql: 9.4

before_script:
  - cp .travis.database.yml config/database.yml
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c 'create database "bookmark";'
  - psql -U postgres bookmark -c 'create extension "uuid-ossp";'
