language: java
jdk:
- oraclejdk8

sudo: required

env:
  global:
    - PGPORT=5432

services:
  - postgresql

addons:
  apt:
    packages:
    - postgresql-9.4
    - postgresql-contrib-9.4
  postgresql: 9.4

before_script:
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c 'create database "bookmark";'
  - psql -U postgres bookmark -c 'create extension "uuid-ossp";'
  - psql -c "CREATE USER bookmark_user WITH PASSWORD 'bookmarks_pasword';" -U postgres
