language: java
jdk:
- oraclejdk8

sudo: required

env:
  global:
    - PGPORT=5432

services:
  - postgresql

addons:
  apt:
    packages:
    - postgresql-9.6
    - postgresql-contrib-9.6
    - postgresql-server-dev-9.6
  postgresql: 9.6

before_script:
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c 'create database "bookmarks";'
  - psql -c "CREATE USER bookmark_user WITH PASSWORD 'bookmarks_password';" -U postgres
  - psql -c "grant all privileges on database bookmarks to bookmark_user;" -U postgres
